### ISSUE TITLE
Namespace Load Error

### ISSUE THREAD

**Issue by burnsal** [cran/torchvisionlib#1]
Hello,

I am running into issues loading the torchvisionlib library into R Studio. It looks like the package installs without issue, but when I try to call it with the `library()` command I receive the following error:
```
Error: package or namespace load failed for ‘torchvisionlib’:
 .onLoad failed in loadNamespace() for 'torchvisionlib', details:
  call: dyn.load(lib_path("torchvision"), local = FALSE)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/torchvisionlib//lib/libtorchvision.dylib':
  dlopen(/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/torchvisionlib//lib/libtorchvision.dylib, 0x000A): Library not loaded: '/usr/local/opt/libpng/lib/libpng16.16.dylib'
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/torchvisionlib/lib/libtorchvision.dylib'
  Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)
```

I tried uninstalling and reinstalling the package with the same result. I am running R 4.3.1, RStudio 2023.6.0.421 on a Mac, os:   x86_64-apple-darwin20. I use the package successfully on a Windows machine; is there a Mac compatibility issue? 

Please let me know if I can provide any additional information to help troubleshoot. Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
